'use client';
import React from 'react';
import { useRunArtifacts } from '@/features/artifacts/hooks';
import { useArtifactsStore } from '@/features/artifacts/store';
import { ArtifactCard } from '@/components/domain/ArtifactCard';
import { ArtifactPreviewModal } from '@/components/domain/ArtifactPreviewModal';
import { EmptyState } from '@/components/core/EmptyState';
import { Skeleton } from '@/components/core/Skeleton';
import { Banner } from '@/components/core/Banner';
import type { ArtifactType } from '@/lib/schemas/artifact';
import styles from './artifacts.module.css';

const FEATURE_ENABLED = process.env.NEXT_PUBLIC_FEATURE_ARTIFACTS_ENABLED !== 'false';

const TYPE_LABELS: Record<ArtifactType | 'all', string> = {
  all: 'All',
  patch: 'Patches',
  file: 'Files',
  screenshot: 'Screenshots',
  report: 'Reports',
  download: 'Downloads',
  image: 'Images',
  video: 'Videos',
  log: 'Logs',
};

export default function RunArtifactsPage({ params }: { params: { runId: string } }) {
  const { runId } = params;
  const { typeFilter, setTypeFilter, previewId, setPreviewId } = useArtifactsStore();
  const { data: artifacts = [], isLoading, error } = useRunArtifacts(runId);

  const typesPresent = Array.from(new Set(artifacts.map((a) => a.type))) as ArtifactType[];
  const filtered = typeFilter === 'all' ? artifacts : artifacts.filter((a) => a.type === typeFilter);
  const previewArtifact = previewId ? artifacts.find((a) => a.id === previewId) ?? null : null;

  if (!FEATURE_ENABLED) {
    return <Banner variant="info">Artifacts are feature-flagged. Set NEXT_PUBLIC_FEATURE_ARTIFACTS_ENABLED=true.</Banner>;
  }

  return (
    <div className={styles.page}>
      <div className={styles.toolbar}>
        <span className={styles.heading}>Artifacts</span>
        <div className={styles.filters} role="group" aria-label="Filter by type">
          {(['all', ...typesPresent] as (ArtifactType | 'all')[]).map((t) => (
            <button
              key={t}
              className={[styles.filterBtn, typeFilter === t ? styles['filterBtn--active'] : ''].filter(Boolean).join(' ')}
              onClick={() => setTypeFilter(t)}
              aria-pressed={typeFilter === t}
            >
              {TYPE_LABELS[t]}
            </button>
          ))}
        </div>
      </div>

      {error && (
        <Banner variant="error">
          Failed to load artifacts: {error instanceof Error ? error.message : 'Error'}
        </Banner>
      )}

      {isLoading ? (
        <div className={styles.grid}>
          {Array.from({ length: 6 }).map((_, i) => (
            <Skeleton key={i} width="100%" height={220} borderRadius="12px" />
          ))}
        </div>
      ) : filtered.length === 0 ? (
        <EmptyState
          title={typeFilter === 'all' ? 'No artifacts yet' : `No ${TYPE_LABELS[typeFilter].toLowerCase()} yet`}
          description="Artifacts generated by the agent will appear here."
          icon="📦"
        />
      ) : (
        <div className={styles.grid}>
          {filtered.map((artifact) => (
            <ArtifactCard
              key={artifact.id}
              artifact={artifact}
              onPreview={setPreviewId}
            />
          ))}
        </div>
      )}

      <ArtifactPreviewModal
        artifact={previewArtifact}
        onClose={() => setPreviewId(null)}
      />
    </div>
  );
}
